// Copyright (C) 2026 Massimo Cavalleri <massimo.cavalleri@gmail.com>
//
// This file is part of shfm.
//
// shfm is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// shfm is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with shfm.  If not, see <https://www.gnu.org/licenses/>.

// Package opener resolves and launches the desktop's default application
// for a file, following the XDG Desktop Entry / MIME Applications
// Association specifications directly (parsing mimeapps.list and .desktop
// files) — no dependency on the xdg-open script or any other external
// command for the *resolution* step. Actually launching the chosen
// application is, necessarily, done via os/exec (that's simply how you run
// another program), exactly as any file manager does.
package opener

import (
	"bufio"
	"fmt"
	"mime"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"syscall"
)

// App describes an installed application discovered from a .desktop file.
type App struct {
	ID       string // desktop file base name, e.g. "org.gnome.eog.desktop"
	Name     string
	Exec     string // raw Exec= value, with %f/%u/... placeholders still in place
	Terminal bool
}

func appDirs() []string {
	var dirs []string
	if dataHome := os.Getenv("XDG_DATA_HOME"); dataHome != "" {
		dirs = append(dirs, filepath.Join(dataHome, "applications"))
	} else if home, err := os.UserHomeDir(); err == nil {
		dirs = append(dirs, filepath.Join(home, ".local", "share", "applications"))
	}
	if dataDirs := os.Getenv("XDG_DATA_DIRS"); dataDirs != "" {
		for _, d := range strings.Split(dataDirs, ":") {
			if d != "" {
				dirs = append(dirs, filepath.Join(d, "applications"))
			}
		}
	} else {
		dirs = append(dirs, "/usr/local/share/applications", "/usr/share/applications")
	}
	return dirs
}

func configDirs() []string {
	var dirs []string
	if configHome := os.Getenv("XDG_CONFIG_HOME"); configHome != "" {
		dirs = append(dirs, configHome)
	} else if home, err := os.UserHomeDir(); err == nil {
		dirs = append(dirs, filepath.Join(home, ".config"))
	}
	if configDirsEnv := os.Getenv("XDG_CONFIG_DIRS"); configDirsEnv != "" {
		dirs = append(dirs, strings.Split(configDirsEnv, ":")...)
	} else {
		dirs = append(dirs, "/etc/xdg")
	}
	return dirs
}

// MimeType guesses a MIME type for name from its extension, using Go's
// stdlib mime package (which itself also reads /etc/mime.types when
// present); falls back to a generic type when unknown.
func MimeType(name string) string {
	ext := filepath.Ext(name)
	if ext == "" {
		return "application/octet-stream"
	}
	if t := mime.TypeByExtension(ext); t != "" {
		if i := strings.IndexByte(t, ';'); i >= 0 {
			t = t[:i]
		}
		return t
	}
	return "application/octet-stream"
}

// DefaultApp looks up the application to open mimeType with by reading
// mimeapps.list/mimeinfo.cache (user config first, then system-wide),
// following the freedesktop.org "Default Applications for MIME types"
// association spec. Returns (App, true) on success.
//
// Three passes, strongest signal first, each covering every priority level
// (user config, then system) before moving to the next, weaker one:
//
//  1. mimeapps.list's [Default Applications] — an explicit, real default
//     (e.g. set via a desktop's "Open With… → Always use this
//     application").
//  2. mimeapps.list's [Added Associations] — an app the user has at least
//     once chosen to open this type with (a plain "Open With…", not marked
//     as the default) but that a desktop environment's own resolver (e.g.
//     GIO, which Nautilus/Thunar use) will still often pick over anything
//     else when no real default is set.
//  3. mimeinfo.cache's [MIME Cache] — just "an app that CAN open this",
//     generated by update-desktop-database; picking this over an unresolved
//     tier-1/2 entry from a *lower*-priority mimeapps.list would let an
//     arbitrary "capable" app pre-empt a real, if lower-priority, choice.
func DefaultApp(mimeType string) (App, bool) {
	var mimeappsLists, cacheLists []string
	for _, d := range configDirs() {
		mimeappsLists = append(mimeappsLists, filepath.Join(d, "mimeapps.list"))
	}
	for _, d := range appDirs() {
		mimeappsLists = append(mimeappsLists, filepath.Join(d, "mimeapps.list"))
		cacheLists = append(cacheLists, filepath.Join(d, "mimeinfo.cache"))
	}
	for _, section := range []string{"Default Applications", "Added Associations"} {
		for _, listPath := range mimeappsLists {
			if desktopID, ok := lookupAssociation(listPath, section, mimeType); ok {
				if app, ok := findDesktopFile(desktopID); ok {
					return app, true
				}
			}
		}
	}
	for _, listPath := range cacheLists {
		if desktopID, ok := lookupAssociation(listPath, "MIME Cache", mimeType); ok {
			if app, ok := findDesktopFile(desktopID); ok {
				return app, true
			}
		}
	}
	return App{}, false
}

// lookupAssociation parses a mimeapps.list/mimeinfo.cache-style INI file
// looking for mimeType under the given section (e.g. "Default
// Applications", "Added Associations", "MIME Cache"), returning the first
// associated .desktop file ID.
func lookupAssociation(path, section, mimeType string) (string, bool) {
	f, err := os.Open(path)
	if err != nil {
		return "", false
	}
	defer f.Close()

	inRelevantSection := false
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		if strings.HasPrefix(line, "[") && strings.HasSuffix(line, "]") {
			inRelevantSection = line[1:len(line)-1] == section
			continue
		}
		if !inRelevantSection {
			continue
		}
		key, val, ok := strings.Cut(line, "=")
		if !ok || strings.TrimSpace(key) != mimeType {
			continue
		}
		// Value can be a ';'-separated list; take the first entry.
		first := strings.TrimSpace(strings.SplitN(val, ";", 2)[0])
		if first != "" {
			return first, true
		}
	}
	return "", false
}

// findDesktopFile locates and parses a .desktop file by ID (as referenced
// by mimeapps.list, e.g. "org.gnome.eog.desktop") across the standard XDG
// application directories.
func findDesktopFile(desktopID string) (App, bool) {
	for _, dir := range appDirs() {
		path := filepath.Join(dir, desktopID)
		if app, ok := parseDesktopFile(path); ok {
			app.ID = desktopID
			return app, true
		}
	}
	return App{}, false
}

func parseDesktopFile(path string) (App, bool) {
	f, err := os.Open(path)
	if err != nil {
		return App{}, false
	}
	defer f.Close()

	var app App
	inEntry := false
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		if strings.HasPrefix(line, "[") && strings.HasSuffix(line, "]") {
			inEntry = line == "[Desktop Entry]"
			continue
		}
		if !inEntry {
			continue
		}
		key, val, ok := strings.Cut(line, "=")
		if !ok {
			continue
		}
		switch strings.TrimSpace(key) {
		case "Name":
			if app.Name == "" {
				app.Name = strings.TrimSpace(val)
			}
		case "Exec":
			app.Exec = strings.TrimSpace(val)
		case "Terminal":
			app.Terminal = strings.TrimSpace(val) == "true"
		case "NoDisplay", "Hidden":
			if strings.TrimSpace(val) == "true" {
				return App{}, false
			}
		}
	}
	if app.Exec == "" {
		return App{}, false
	}
	if app.Name == "" {
		app.Name = strings.TrimSuffix(filepath.Base(path), ".desktop")
	}
	app.ID = filepath.Base(path)
	return app, true
}

// ListApps scans the standard application directories for installed,
// launchable .desktop entries (skipping NoDisplay/Hidden ones), sorted by
// name — used to populate the "choose an application" dialog when no
// default is configured yet.
func ListApps() []App {
	seen := map[string]bool{}
	var apps []App
	for _, dir := range appDirs() {
		entries, err := os.ReadDir(dir)
		if err != nil {
			continue
		}
		for _, e := range entries {
			if e.IsDir() || !strings.HasSuffix(e.Name(), ".desktop") {
				continue
			}
			if seen[e.Name()] {
				continue
			}
			if app, ok := parseDesktopFile(filepath.Join(dir, e.Name())); ok {
				seen[e.Name()] = true
				apps = append(apps, app)
			}
		}
	}
	sort.Slice(apps, func(i, j int) bool { return strings.ToLower(apps[i].Name) < strings.ToLower(apps[j].Name) })
	return apps
}

// expandExec substitutes the (limited) field codes shfm actually needs
// (%f/%F/%u/%U -> the target file path; any other %x is dropped) in a
// .desktop Exec= value, and splits it into argv. This is a deliberately
// small subset of the full Desktop Entry Exec parsing rules — enough for
// the overwhelming majority of real-world .desktop files.
func expandExec(execLine, targetPath string) []string {
	fields := strings.Fields(execLine)
	out := make([]string, 0, len(fields))
	substituted := false
	for _, f := range fields {
		switch f {
		case "%f", "%F", "%u", "%U":
			out = append(out, targetPath)
			substituted = true
		case "%i", "%c", "%k":
			// icon/name/file placeholders we don't have meaningful values
			// for: drop them.
		default:
			if strings.HasPrefix(f, "%") {
				continue
			}
			out = append(out, f)
		}
	}
	if !substituted {
		out = append(out, targetPath)
	}
	return out
}

// buildCmd prepares (without starting) the command to launch app on
// targetPath, detached from shfm's own process group/terminal.
func buildCmd(app App, targetPath string) (*exec.Cmd, error) {
	argv := expandExec(app.Exec, targetPath)
	if len(argv) == 0 {
		return nil, fmt.Errorf("empty Exec= line for %s", app.Name)
	}
	cmd := exec.Command(argv[0], argv[1:]...)
	cmd.Stdin, cmd.Stdout, cmd.Stderr = nil, nil, nil
	cmd.SysProcAttr = &syscall.SysProcAttr{Setsid: true}
	return cmd, nil
}

// Launch starts app with targetPath as its argument, detached from shfm
// (its own process group, not waited on), so shfm keeps running normally.
func Launch(app App, targetPath string) error {
	cmd, err := buildCmd(app, targetPath)
	if err != nil {
		return err
	}
	if err := cmd.Start(); err != nil {
		return fmt.Errorf("could not launch %s: %w", app.Name, err)
	}
	go cmd.Wait() // reap the child without blocking shfm
	return nil
}

// LaunchAndWait is like Launch, but blocks the calling goroutine until app
// exits — for callers that need to react afterwards, e.g. syncing a local
// temp copy of a remote file back to its source once the user is done
// editing it. This is a best-effort signal for "done editing": an app that
// hands off to an already-running instance (common for single-instance GUI
// apps) may exit immediately, well before the user actually closes the
// document in that other instance.
func LaunchAndWait(app App, targetPath string) error {
	cmd, err := buildCmd(app, targetPath)
	if err != nil {
		return err
	}
	if err := cmd.Start(); err != nil {
		return fmt.Errorf("could not launch %s: %w", app.Name, err)
	}
	return cmd.Wait()
}

// SaveDefaultApp records app as the default for mimeType in the user's
// mimeapps.list ($XDG_CONFIG_HOME/mimeapps.list), creating or updating the
// "[Default Applications]" section. Best-effort: on I/O failure the choice
// simply won't be remembered next time.
func SaveDefaultApp(mimeType string, app App) error {
	dirs := configDirs()
	if len(dirs) == 0 {
		return fmt.Errorf("no config directory available")
	}
	path := filepath.Join(dirs[0], "mimeapps.list")

	lines, _ := readLines(path)
	lines = upsertAssociation(lines, mimeType, app.ID)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(strings.Join(lines, "\n")+"\n"), 0o644)
}

func readLines(path string) ([]string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	return strings.Split(strings.TrimRight(string(data), "\n"), "\n"), nil
}

// upsertAssociation sets mimeType=desktopID under "[Default Applications]"
// in an in-memory mimeapps.list, adding the section/key if missing or
// replacing the value if already present.
func upsertAssociation(lines []string, mimeType, desktopID string) []string {
	const section = "[Default Applications]"
	sectionIdx := -1
	keyIdx := -1
	nextSectionIdx := len(lines)
	for i, line := range lines {
		trimmed := strings.TrimSpace(line)
		if trimmed == section {
			sectionIdx = i
			continue
		}
		if sectionIdx >= 0 && keyIdx == -1 && strings.HasPrefix(trimmed, "[") && strings.HasSuffix(trimmed, "]") {
			nextSectionIdx = i
			break
		}
		if sectionIdx >= 0 {
			key, _, ok := strings.Cut(trimmed, "=")
			if ok && strings.TrimSpace(key) == mimeType {
				keyIdx = i
			}
		}
	}
	entry := mimeType + "=" + desktopID + ";"
	switch {
	case sectionIdx == -1:
		if len(lines) == 1 && lines[0] == "" {
			lines = nil
		}
		lines = append(lines, section, entry)
	case keyIdx != -1:
		lines[keyIdx] = entry
	default:
		out := make([]string, 0, len(lines)+1)
		out = append(out, lines[:nextSectionIdx]...)
		out = append(out, entry)
		out = append(out, lines[nextSectionIdx:]...)
		lines = out
	}
	return lines
}
